spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationInMs: ${JWT_EXPIRATION}
server:
  error:
    include-message: always
    include-stacktrace: never
